### ISSUE TITLE
Adapt changes to Data_specification_physical_unit when possible

### ISSUE THREAD

**Issue by s-heppner** [aas-core-works/aas-core-meta#188]
Adapt the changes of the spec DotAAS 3b whenever it gets released

**Comment by g1zzm0** [comment]
Can you please specify what you expect?

**Comment by s-heppner** [comment]
Sadly, I cannot, considering that Part 3b of DotAAS is not finished yet. This issue is meant to track one of the todos we still need to do for the v3.0 release.

**Comment by g1zzm0** [comment]
Right, in the end we have to adapt every changes in all 5, 6, or what now documents ;)

**Comment by s-heppner** [comment]
After newest deliberation, it has been concluded to exclude Data_spec_physical_unit from the v3.0 release. Therefore, we should remove the classes as well
