### ISSUE TITLE
Resolve confusion around AASd-119 and AASd-129

### ISSUE THREAD

**Issue by s-heppner** [aas-core-works/aas-core-meta#204]
I think those two constraints have been thrown around and mixed up several times. Therefore:

- Research and document their differences here
- Check their occurences in the code
- Fix the implementations as far as possible (considering parts of it may not be possible to check)
- Document what is implemented and what not (also think of the module docstring)

**Comment by s-heppner** [comment]
## Constraint AASd-119

> If any Qualifier/kind value of a Qualifiable/qualifier is equal to TemplateQualifier and the qualified element inherits from "hasKind", the qualified element shall be of kind Template (HasKind/kind = "Template").

This only applies to `Submodel`s, since this is the only occurrance of an object that is `Qualifiable` and `HasKind` at the same time.  The invariant checking, if `Submodel.qualifier` is a `TEMPLATE` qualifier is possible.

## Constraint AASd-129

> If any Qualifier/kind value of a SubmodelElement/qualifier (attribute qualifier inherited via Qualifiable) is equal to TemplateQualifier, the submodel element shall be part of a submodel template, i.e. a Submodel with Submodel/kind (attribute kind inherited via HasKind) value equal to Template.

This constraint is difficult to check, considering we would have to recursively either go up the parents of a `Qualifiable` until we reach a `Submodel` object, or, starting from the `Submodel` down through the `submodel_elements` and check each of the children's qualifiers.

**Comment by mristin** [comment]
@s-heppner We can have a look at this one when I'm back in town. Recursive constraints shouldn't be a problem.
