### ISSUE TITLE
Abbreviations may contain non-capital letters

### ISSUE THREAD

**Issue by s-heppner** [aas-core-works/aas-core-meta#214]
There exist a number of abbreviations (AASiD, SaaS, etc.) that are not fully capitalized.  
If this is not a problem with the way naming is handeled, then disregard this issue. Otherweise, long-term, we need to find a way to deal with those, even if they do not occur in v3.0 of the spec.

**Comment by mristin** [comment]
This is currently implemented in V3 as follows: https://github.com/aas-core-works/aas-core-meta/blob/9e6d926f6ee5deb660a4ed189d78d9c75289bc3e/tests/test_v3.py#L860

In a nutshell, we define for each lowercase version the expected casing as abbreviation.
