### ISSUE TITLE
Unclear formulation in module docstring

### ISSUE THREAD

**Issue by s-heppner** [aas-core-works/aas-core-meta#232]
> The enumeration [AAS_submodel_elements](https://aas-core-works.github.io/aas-core-meta/v3/AAS_submodel_elements.html) is used in two different contexts. One context is the definition of key types in a reference. Another context is the definition of element types in a [Submodel_element_list](https://aas-core-works.github.io/aas-core-meta/v3/Submodel_element_list.html). It is very counter-intuitive to see the type of [Submodel_element_list.type_value_list_element](https://aas-core-works.github.io/aas-core-meta/v3/Submodel_element_list.html#property-type_value_list_element) as [Key_types](https://aas-core-works.github.io/aas-core-meta/v3/Key_types.html) even though an invariant might specify that it is an element of [AAS_submodel_elements](https://aas-core-works.github.io/aas-core-meta/v3/AAS_submodel_elements.html).

I don't understand what is meant here. This description may also be outdated for v3.0.

**Comment by mristin** [comment]
I think it is still valid. We introduced a separate constant set as the name `Key_types` would have been very confusing in the abovementioned context.

**Comment by mristin** [comment]
P.S. please have a closer look where these types and constant sets are used.

**Comment by mristin** [comment]
@s-heppner that is correct.

**Comment by s-heppner** [comment]
In that case, I proposed a reworked formulation in #233 that may be less confusing to me
