### ISSUE TITLE
Document why `Submodel_element` does not include `Data_element` as concrete descendant

### ISSUE THREAD

**Issue by s-heppner** [aas-core-works/aas-core-meta#245]
During review, the question to document why `Submodel_element` does not include `Data_element` as concrete descendant came up. Of course, this is because `Data_element` is an abstract descendant, not a concrete one. 

We suggest to list all descendants of a class in the generated html documentation, rather than just the concrete ones, for an easier overview of the inheritance tree.

**Comment by mristin** [comment]
Fixed by #267.
