### ISSUE TITLE
Inconsistency to specification at `matches_RFC_8089_path`

### ISSUE THREAD

**Issue by s-heppner** [aas-core-works/aas-core-meta#269]
The [function](https://github.com/aas-core-works/aas-core-meta/blob/8f18a8cc586dac01eb5c0b2d75ca8f8c52be0484/aas_core_meta/v3.py#L231) `matches_RFC_8089_path` is supposed to check for a valid path URI. 

Nevertheless, it does not allow for relative paths, which are necessary to reference supplementary files in AASX-packages:
[PathType definition](https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf#Page=97)
[AASX-Specification for Supplementary Files](https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01005-3-0_SpecificationAssetAdministrationShell_Part5_AASXPackageFileFormat.pdf#Page=20)

Therefore, it is absolutely necessary to allow for relative paths in `Path_type`.

**Comment by mristin** [comment]
The relative paths in RFC 8089 start with a dot. The pattern has been automatically translated from ABNF in the RFC document.

**Comment by s-heppner** [comment]
Alright, then I assume the problem lies with the outdated version of our AASX-Writer. I'll double check this.

**Comment by mristin** [comment]
Also this: https://superuser.com/a/1763925

It does seem plausible that RFC 8089 does not allow relative paths.

**Comment by s-heppner** [comment]
The specification about [PathType](https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf#Page=97):

> Note: for any string conformant to RFC8089, the "file" URI scheme (for relative and absolute file paths) applies.

I've tried checking RFC 8089 more extensively and [this](https://datatracker.ietf.org/doc/html/rfc8089#appendix-E.2.1) is the only mention I found of relative paths:

>      base URI:   file:///c:/path/to/file.txt
>      rel. ref.:  /some/other/thing.bmp
>      resolved:   file:///c:/some/other/thing.bmp
>
>      base URI:   file:///c:/foo.txt
>      rel. ref.:  ../bar.txt
>      resolved:   file:///c:/bar.txt

The relative paths seem not to be part of the formal specification, their existence relative to a base RFC 8089 URI does seem to be acknowledged, though.

**Comment by mristin** [comment]
I'll close the issue as it seems resolved. Please feel free to re-open.

**Comment by mristin** [comment]
@s-heppner This issue pops up again and again. Are there any news from the AAS WS? Are RFC 8089 enforced or not?

**Comment by s-heppner** [comment]
Let's talk about this in person when we next speak

**Comment by mristin** [comment]
As far as I know, this issue will be fixed in V3.1, but no changes in V3 are expected. I'm closing the issue as it is not related to V3, and we will consider it anyhow when we formalize V3.1.
