### ISSUE TITLE
Question: When will v3 "final" be available?

### ISSUE THREAD

**Issue by wiresio** [aas-core-works/aas-core-meta#270]
Currently aas-core-meta and software relying on it, e.g., AASX Package Explorer, seems to be stuck at v3rc02. To enable interoperability tests with e.g., Eclipse Basyx, it would be great to come to a final v3 version. What are the plans for this?

**Comment by g1zzm0** [comment]
The version 3.0 is already available and has been published on the 19th of April 2023. You can find it [here](https://github.com/aas-core-works/aas-core-meta/blob/main/aas_core_meta/v3.py).
