### ISSUE TITLE
Implementation of the constraint AASc-3a-010

### ISSUE THREAD

**Issue by chborntraeger** [aas-core-works/aas-core-meta#279]
An verification error (AASc-3a-010) is raised when value and value list are empty in data specifications. In my understandig its not requeired to set one of them. The constraint only prohibits to set both of them, or am i wrong?

"If DataSpecificationIec61360/value is not empty, DataSpecificationIec61360/valueList shall be empty, and vice versa" (source:  Asset Administration Shell Specification - Part 3a: Data Specification - IEC 61360)

see also [https://github.com/aas-core-works/aas-core3.0-typescript/issues/12](https://github.com/aas-core-works/aas-core3.0-typescript/issues/12)

**Comment by mristin** [comment]
@chborntraeger thanks again for spotting and reporting the issue!

@sebbader-sap @s-heppner what do you say? Again inclusive or as in #278?

**Comment by s-heppner** [comment]
The [spec here](https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01003-a-3-0_SpecificationAssetAdministrationShell_Part3a_DataSpecification_IEC61360.pdf#Page=22) says:

>  If DataSpecificationIec61360/value is not empty, DataSpecificationIec61360/valueList shall be empty, and vice versa.

But adds two notes: 

> Note 1: it is also possible that both DataSpecificationIec61360/value and SpecificationIec61360/valueList are empty. This is the case for concept descriptions that define the semantics of a property but do not have an enumeration (valueList) as
data type.
> Note 2: although it is possible to define a concept description for a value list, it is not possible to reuse this value list. It is only possible to directly add a value list as data type to a specific semantic definition of a property

Based on this, I agree with @sebbader-sap's interpretation.
