### ISSUE TITLE
Include codes according to ISO 3166 in BCP 47?

### ISSUE THREAD

**Issue by mristin** [aas-core-works/aas-core-meta#282]
Following the issue raised in https://github.com/aas-core-works/aas-core3.0-testgen/issues/16, we should probably consider materializing all the country codes in the formalized specs.

I imagine the invalid BCP47 tags to be a common source of interoperability problems as it is so easy to get them wrong (see the issue above, `en-UK` is invalid and should read `en-GB`).

On the other hand, we have to update the list continuously as soon as new languages are recognized. I am not 100%, but I can also imagine that language codes might be deleted eventually, so the specs are not backwards compatible.

IMO, it is probably best if we simply assume that the AAS is tied to the most recent ISO 3166 codes, and simply update the regularly in patch versions of AAS specs version.

@zrgt @sebbader @g1zzm0 @s-heppner any thoughts on this?

**Comment by mristin** [comment]
See also: https://github.com/admin-shell-io/aas-specs/issues/293

**Comment by zrgt** [comment]
@mristin I find it is a good idea. May be we should wait until we get more clarity on the question: https://github.com/admin-shell-io/aas-specs/issues/293

We might also want to think about including ISO 639 and ISO 15924 codes to make it a well-rounded package.

**Comment by mristin** [comment]
@sebbader if we are to implement this change, we should probably tie it all together with changes necessary for issues #288 and #289.

**Comment by mristin** [comment]
I'll close the issue for now. We do not have the woman-power to update the list on a regular basis. Having an outdated list can wreak havoc on clients due to false negatives. Their language codes would be correct, but we would flag them as incorrect.
