### ISSUE TITLE
Invariant of `Lang_string_short_name_type_IEC_61360` inconsistent

### ISSUE THREAD

**Issue by mristin** [aas-core-works/aas-core-meta#288]
Origin: https://github.com/aas-core-works/aas-core-codegen/issues/413

@mrumur wrote:
> The Verification inside TransformLangStringShortNameTypeIec61360 checks for a maximum length of 18 but should be 64 according to the Spec.
> Also the Errormessage returns a maximum length of 1023 instead of the used 18.

@zrgt @s-heppner Could you please have a look?

@sebbader This would also impact the schemas. We should release a patch version of the schemas once we fixed this wave of bugs.

Also related to #289.

**Comment by zrgt** [comment]
According to the [Spec](https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01003-a-3-0_SpecificationAssetAdministrationShell_Part3a_DataSpecification_IEC61360.pdf#page=41) the `Lang_string_short_name_type_IEC_61360 ` should be <= 18

**Comment by BirgitBoss** [comment]
Exactly, according to the spec 01003-a-3-0 Data Specification - IEC 61360  ShortNameTypeIec61360 is limited to max 18 char and min 1 char. So
https://aas-core-works.github.io/aas-core-meta/v3/LangStringShortNameTypeIec61360.html is ok.

Only the error message needs to be corrected it seems to me.
