### ISSUE TITLE
[BUG] link and information not available for MatchesBcp47.html

### ISSUE THREAD

**Issue by BirgitBoss** [aas-core-works/aas-core-meta#292]
https://aas-core-works.github.io/aas-core-meta/v3/Bcp47LanguageTag.html

The value must represent a value language tag conformant to BCP 47.
[MatchesBcp47](https://aas-core-works.github.io/aas-core-meta/v3/MatchesBcp47.html)(
    self
)
Clicking the link raises 404 file not found error

MatchesBcp47.html is listed n the index only

**Comment by mristin** [comment]
Thanks for reporting, @BirgitBoss!
