### ISSUE TITLE
Constraint AASd-120 is missing

### ISSUE THREAD

**Issue by BirgitBoss** [aas-core-works/aas-core-meta#294]
Constraint AASd-120: idShort of submodel elements being a direct child of a SubmodelElementList shall not be specified.

is not listed in https://aas-core-works.github.io/aas-core-meta/v3/index.html

Source: https://github.com/admin-shell-io/aas-specs-api/issues/112

Additionally https://github.com/admin-shell-io/aas-specs-api/issues/112 is asking for validation of AASd-117 and AASd-120. I assume these two constraints belong to those we do not validate/that cannot be validated?

**Comment by mristin** [comment]
@BirgitBoss thanks for reporting the issue!

The invariant is indeed specified:
https://aas-core-works.github.io/aas-core-meta/v3/SubmodelElementList.html#invariants

However, we mistakenly omitted to add it to the appropriate class description.

@s-heppner could you please have a look where the appropriate constraint should be added in the docstrings in aas-core-meta?

> Additionally https://github.com/admin-shell-io/aas-specs-api/issues/112 is asking for validation of AASd-117 and AASd-120. I assume these two constraints belong to those we do not validate/that cannot be validated?

As a matter of fact, both AASd-120 and AASd-117 are validated. Please see: https://github.com/aas-core-works/aas-core-meta/blob/main/aas_core_meta/v3.py
and search for `AASd-120` and `AASd-117`.

**Comment by s-heppner** [comment]
I've added the missing documentation of `AASd-120` in #295 

`AASd-117` is indeed implemented and documented [here](https://aas-core-works.github.io/aas-core-meta/v3/IdShortType.html).

**Comment by s-heppner** [comment]
However, the way I understand [aas-specs-api#112](https://github.com/admin-shell-io/aas-specs-api/issues/112), is that these two constraints do not appear in the JSON-schema, when they should, for the sake of the API implementation. 

In that case, that issue is not of aas-core-meta, but one of [aas-core-codegen](https://github.com/aas-core-works/aas-core-codegen).

**Comment by mristin** [comment]
@s-heppner just a status update from my side: I'm finishing the c++ generator, and afterwards I'll merge in all the pending aas-core-meta and aas-core-testgen PRs.
