### ISSUE TITLE
Proposal: Think about a GraphQL Metamodel Schema as well for aas-core-meta

### ISSUE THREAD

**Issue by foprs** [aas-core-works/aas-core-meta#297]
I am proposing to consider as well a GraphQL schema for the AAS metamodel for aas-core-meta.

This would open the "AAS world" for developers that are used to work with GraphQL API's.

There is already a draft version available that could be integrated into aas-core-meta, see attachment

[aas_metamodel_v3_0_0.txt](https://github.com/aas-core-works/aas-core-meta/files/13717275/aas_metamodel_v3_0_0.txt)

**Comment by mristin** [comment]
Hi @foprs ,
Thanks for the idea! We are already working on the formalization and transpilation of the clients/server stubs, see #296.

I'll close this issue and kindly ask future comments to be redirected to #296.
