### ISSUE TITLE
Misleading error message on validation of MultiLanguageProperty

### ISSUE THREAD

**Issue by CHRiSLY78** [aas-core-works/aas-core-meta#299]
The value of a MultiLanguageProperty must have unique entries for each language.

The invariant checking this is currently named "Value specifies no duplicate languages." 
https://aas-core-works.github.io/aas-core-meta/v3/MultiLanguageProperty.html

An according validation error log enrty would be: "Invariant violated:Value specifies no duplicate languages."

This is misleading since it may be interpreted as if the current value does not but should specify duplicate languages.
(At least I did so when I first encountered this ;))

Suggestion: please name the invariant "Value must specifiy no duplicate languages." or even better "Value must specify unique languages."

**Comment by mristin** [comment]
Thanks, @CHRiSLY78!

We are currently busy around Christmas/New Year, but I'll fix this issue in January 2024 together with a couple of other minor pending issues.
