### ISSUE TITLE
Wrong configuration for namespace in reverse proxy

### ISSUE THREAD

**Issue by mhrimaz** [aas-core-works/aas-core-meta#300]
When trying to resolve https://admin-shell.io/aas/3/0/ request would be redirected to https://aas-core-works.github.io/aas-core-meta/v3/.html which should be https://aas-core-works.github.io/aas-core-meta/v3/

However the content negotiation is fine and for 'text/turtle' it returns the Ontology of AAS which is great.

**Comment by mristin** [comment]
@sebbader @sebbader-sap can you please adjust the server?

**Comment by mristin** [comment]
I've just written an email to @sebbader; I think he has not see this issue yet.

**Comment by mristin** [comment]
I will close this issue as it is not directly related to aas-core-works, but to a reverse proxy maintained outside aas-core-works.

**Comment by sebbader-sap** [comment]
@mhrimaz good observation, let me see what I can do.

(indeed, haven't seen this issue last year)

**Comment by sebbader-sap** [comment]
@mhrimaz please try it again. I added a quick-and-dirty fix that seems to do the job.
