### ISSUE TITLE
RelationshipElement abstract

### ISSUE THREAD

**Issue by sebbader** [aas-core-works/aas-core-meta#97]
One thing I have noticed:
https://github.com/admin-shell-io/aas-specs/blob/c7103b7fdb5c760b04378420b5d7e6e4a34ea427/schemas/rdf/shacl-schema.ttl#L929 says "An aas:RelationshipElement is a abstract class"
It's not (anymore?) and I could also not find this text in the python file. Can you update this line?

(Background: we are scanning the SHACL messages for 'abstract' to extract information which classes shall be instantiable. Not the right way to go, I know. But for now the only way to get this information.)

**Comment by mristin** [comment]
Hi @sebbader ,
We indeed marked `RelationshipElement` as abstract:
https://github.com/aas-core-works/aas-core-meta/blob/7663ba0c80b56758ce66d9960a99787a895f602f/aas_core_meta/v3rc2.py#L2239

I double-checked in the final version of the book -- it is indeed not abstract anymore. I'll fix this on Wednesday.
